-- ============================================================
-- Unveil — card content seed
-- Generated from web/cards.json by `npm run seed`. Do not hand-edit:
-- regenerate instead, or the two will drift apart.
--
-- Content v2.0.0 · language en · 36 cards
-- (20 real, 10 fake, 6 audience)
--
-- Safe to re-run. Existing rows are updated in place, so a text fix
-- reaches live games without disturbing any deal that references a slug.
-- ============================================================

insert into public.cards (slug, type, headline, clues, why_it_works, verification) values
  ($uv$4a9f2c$uv$, $uv$real$uv$, $uv$A hospital itemised a new father's bill with a $39.35 charge for “skin to skin after C-section” — a fee for holding his own newborn.$uv$, null, null, $uv$[["Precedent","Itemised hospital bills in private healthcare systems routinely contain micro-charges for standard nursing support that patients never review line by line."],["Context","The father posted a photo of the receipt in 2016. The hospital confirmed the charge, explaining it covered the extra nurse required to monitor the infant in theatre."],["Defense","It sounds like satire precisely because billing has reached the point of itemising a parent holding their child. The hospital's own defence of the charge is what makes it credible."]]$uv$::jsonb),
  ($uv$b17e50$uv$, $uv$real$uv$, $uv$Scientists taught goldfish to drive a motorised robotic vehicle across a room toward targeted food rewards on land.$uv$, null, null, $uv$[["Precedent","Behavioural neuroscientists routinely test spatial mapping across species using land-based apparatus to separate locomotion mechanics from pure navigation skill."],["Context","Published in 2022 by researchers at an Israeli university, using a “fish-operated vehicle” — a tank on wheels that moved according to where the fish swam."],["Defense","Frame it as legitimate ethology: the researchers isolated the fish's ability to navigate visually toward a target in an environment its species never evolved for."]]$uv$::jsonb),
  ($uv$c83d16$uv$, $uv$real$uv$, $uv$A commercial airliner was delayed for hours because a swarm of roughly 20,000 bees settled on the plane's wing.$uv$, null, null, $uv$[["Precedent","Aircraft are uniquely vulnerable to wildlife anomalies. Ground crews handle bird strikes constantly, but a swarm settling on an aerodynamic surface halts everything."],["Context","It happened at a Houston airport gate in 2024. Staff could not simply spray them — a beekeeper was called to relocate the swarm intact."],["Defense","A queen had likely landed on the warm wing and the colony followed her. No airline will taxi with 20,000 insects on a control surface."]]$uv$::jsonb),
  ($uv$7d02ab$uv$, $uv$real$uv$, $uv$Venice banned tourists from feeding pigeons in St Mark's Square, shutting down the birdseed vendors who had operated there for generations.$uv$, null, null, $uv$[["Precedent","Historic European tourist sites absorb millions in structural damage and cleaning costs annually from invasive urban bird populations."],["Context","The ban took effect in 2008. Officials cited the corrosive damage pigeon droppings inflict on marble and the cost of restoring the Basilica's stonework."],["Defense","The city weighed the cleaning bill against the tourism value of the birds and found the pigeons were a net loss. Heritage economics, not whimsy."]]$uv$::jsonb),
  ($uv$e5641f$uv$, $uv$real$uv$, $uv$The Australian military deployed soldiers with machine guns against a population of emus, and withdrew in defeat.$uv$, null, null, $uv$[["Precedent","Interwar agricultural governments treated crop-destroying wildlife as a logistics problem and reached for military solutions when civilian control failed."],["Context","In 1932, Western Australian wheat farmers petitioned for help against roughly 20,000 emus. Soldiers with Lewis guns were sent; the operation was called off."],["Defense","Lean on the specific detail — the birds dispersed into small groups, defeating weapons designed for massed targets. Documented military history, not folklore."]]$uv$::jsonb),
  ($uv$39c7d8$uv$, $uv$real$uv$, $uv$A tavern in Japan employs macaque monkeys as waiters, who deliver drinks to customers and are paid in soybeans.$uv$, null, null, $uv$[["Precedent","Japan has a long tradition of trained-monkey performance, and animal-welfare rules there set working-hour limits that the tavern openly observes."],["Context","The Kayabukiya Tavern in Utsunomiya has done this for years. The monkeys wear uniforms, carry hot towels and drink orders, and work legally restricted short shifts."],["Defense","Point at the regulatory detail. A fabricated story would not include working-hour limits — the mundane bureaucracy is the tell that it is real."]]$uv$::jsonb),
  ($uv$a2f68b$uv$, $uv$real$uv$, $uv$A storage tank burst in Boston and sent a wave of molasses through the streets at around 35 km/h, killing 21 people.$uv$, null, null, $uv$[["Precedent","Early-20th-century industrial tanks were built without engineering review. Catastrophic failure of bulk liquid storage was a recognised hazard of the era."],["Context","January 1919, in the North End. The tank held around 2.3 million gallons. The resulting lawsuit became a landmark case in industrial safety regulation."],["Defense","Argue from the physics: molasses is far denser than water, so the wave carried enormous momentum. The absurdity of the substance says nothing about the deaths."]]$uv$::jsonb),
  ($uv$6be913$uv$, $uv$real$uv$, $uv$New Zealand passed a law granting a river the same legal rights as a human being, with appointed guardians who can sue on its behalf.$uv$, null, null, $uv$[["Precedent","Legal systems already grant personhood to non-humans — corporations have held it for over a century."],["Context","The Whanganui River received legal personhood in 2017, concluding one of the country's longest-running Māori legal claims. Two guardians represent it."],["Defense","Reframe it as property law rather than mysticism: personhood gives the river standing in court, which no environmental statute had managed to provide."]]$uv$::jsonb),
  ($uv$f04c7e$uv$, $uv$real$uv$, $uv$In Switzerland it is illegal to keep a single guinea pig, because solitude is considered a form of animal abuse.$uv$, null, null, $uv$[["Precedent","Several European states regulate the psychological welfare of pets, not merely their physical care."],["Context","Swiss animal-welfare rules classify guinea pigs as social animals that must be kept in pairs. This created a small industry renting companions for bereaved survivors."],["Defense","Lead with the rent-a-guinea-pig detail. It sounds like a joke, which is why players assume it is fabricated — but it is a direct market response to the regulation."]]$uv$::jsonb),
  ($uv$1d5a94$uv$, $uv$real$uv$, $uv$Denmark maintains an official government list of approved baby names, and parents wanting anything else must apply for permission.$uv$, null, null, $uv$[["Precedent","Naming law is a real and unglamorous branch of civil administration across the Nordic countries and Iceland."],["Context","The list runs to tens of thousands of pre-approved names. Applications outside it are reviewed for whether the name would subject the child to ridicule."],["Defense","Frame it as child-protection law rather than authoritarianism. The stated purpose is preventing parents from burdening a child with a name they cannot escape."]]$uv$::jsonb),
  ($uv$8e3b27$uv$, $uv$real$uv$, $uv$An Alaskan town elected a cat as its honorary mayor, a position he held for twenty years.$uv$, null, null, $uv$[["Precedent","Small unincorporated towns with no actual mayoral office frequently create ceremonial titles as tourism draws."],["Context","Stubbs held the honorary post in Talkeetna, Alaska, from 1997 until his death in 2017. The town has no formal mayor, which is exactly why the title was available."],["Defense","Emphasise the loophole — no governmental power was ever transferred to a cat. That distinction is what makes the story survive fact-checking."]]$uv$::jsonb),
  ($uv$05fa6d$uv$, $uv$real$uv$, $uv$A brown bear was formally enlisted in the Polish army during the Second World War, given a rank, and carried artillery ammunition in combat.$uv$, null, null, $uv$[["Precedent","Military units have kept mascots for centuries. The unusual step here was formal enlistment, taken to solve a paperwork problem."],["Context","Wojtek was enlisted so he could travel on a troopship that barred animals. He was given a name, rank and serial number, and served at Monte Cassino in 1944."],["Defense","The bureaucratic motive is the proof. Nobody fabricating a story invents “we made him a private so he'd count as cargo” — that is how real institutions behave."]]$uv$::jsonb),
  ($uv$9c47e2$uv$, $uv$real$uv$, $uv$A penguin living in a Scottish zoo has been knighted and promoted to brigadier in the Norwegian King's Guard.$uv$, null, null, $uv$[["Precedent","Ceremonial military patronage of animals is a live tradition in several European armies, complete with formal promotion parades."],["Context","Sir Nils Olav is the regimental mascot of the Norwegian King's Guard, based at Edinburgh Zoo. He was knighted in 2008 with the approval of the King of Norway."],["Defense","Point to the parade footage and the royal approval. This is a documented state ceremony, not a zoo publicity stunt."]]$uv$::jsonb),
  ($uv$2a80fb$uv$, $uv$real$uv$, $uv$A government poll to name a polar research vessel was won by “Boaty McBoatface”, and officials overruled the public result.$uv$, null, null, $uv$[["Precedent","Open internet naming polls have been hijacked repeatedly. Agencies now write override clauses into the rules in advance."],["Context","The 2016 UK poll drew over 120,000 votes for the joke name. The ship was named after a broadcaster instead, and the winning name went to one of its submarines."],["Defense","The compromise is the credible part. A fabricated story would end at the humiliation — real institutions negotiate their way out."]]$uv$::jsonb),
  ($uv$d6218c$uv$, $uv$real$uv$, $uv$The United States government stores over a billion pounds of surplus cheese in limestone caves in Missouri.$uv$, null, null, $uv$[["Precedent","Agricultural price-support programmes have generated enormous state-held commodity surpluses for decades. The storage has to go somewhere."],["Context","The caves are naturally cool former mines used as commercial cold storage. The stockpile grew out of dairy subsidies that bought excess production to hold prices stable."],["Defense","Argue the economics: it is cheaper to warehouse surplus milk as cheese than to let dairy prices collapse. The cave is the least expensive refrigerator available."]]$uv$::jsonb),
  ($uv$3fb075$uv$, $uv$real$uv$, $uv$The Netherlands closed prisons for lack of inmates and rented cells to Norway and Belgium to keep them staffed.$uv$, null, null, $uv$[["Precedent","Prison capacity is a fixed cost. Closing a facility means losing trained staff who cannot be recalled when demand returns."],["Context","Falling crime rates and sentencing policies favouring alternatives left Dutch facilities under-occupied. Several were leased to neighbouring states."],["Defense","Frame it as workforce protection, not a stunt. The alternative was making prison officers redundant in regions with no other employer."]]$uv$::jsonb),
  ($uv$c19d43$uv$, $uv$real$uv$, $uv$Sweden imports hundreds of thousands of tonnes of garbage from other countries because it does not produce enough of its own to fuel its power plants.$uv$, null, null, $uv$[["Precedent","Waste-to-energy incineration is standard district-heating infrastructure across Scandinavia, and those plants require a continuous fuel supply."],["Context","Aggressive domestic recycling reduced Sweden's burnable waste below plant capacity. Neighbouring countries pay Sweden to take waste they would otherwise landfill."],["Defense","Sweden is paid twice — once to accept the waste, once for the heat it generates. The apparent absurdity is a functioning business model."]]$uv$::jsonb),
  ($uv$70e6ca$uv$, $uv$real$uv$, $uv$A university experiment started in 1927 has produced nine drops of liquid in a century, and nobody witnessed one fall until a webcam caught it.$uv$, null, null, $uv$[["Precedent","Long-duration materials experiments exist specifically to measure properties too slow to observe within a human career."],["Context","The pitch drop experiment at an Australian university shows that pitch, which shatters like a solid when struck, is a fluid of extraordinary viscosity."],["Defense","The detail that sells it is the failure — decades of missed drops, including one lost to a coffee break. Fabrications do not include that kind of anticlimax."]]$uv$::jsonb),
  ($uv$5b8f31$uv$, $uv$real$uv$, $uv$A species of jellyfish can reverse its own ageing, reverting to its juvenile stage and starting its life cycle over, apparently without limit.$uv$, null, null, $uv$[["Precedent","Cellular reprogramming is an established biological mechanism. Several species regenerate whole body structures from differentiated tissue."],["Context","Turritopsis dohrnii transforms adult cells back to an earlier type and settles into a polyp colony under stress. It remains vulnerable to predation and disease."],["Defense","Draw the distinction between immortal and invulnerable. The precision of the claim is evidence it came from a paper rather than a rumour."]]$uv$::jsonb),
  ($uv$ae0294$uv$, $uv$real$uv$, $uv$Finland hosts an annual Wife Carrying World Championship where the winner receives their partner's weight in beer.$uv$, null, null, $uv$[["Precedent","Regional Nordic sporting championships built around deliberately absurd disciplines are a well-established summer tourism format."],["Context","The event runs in Sonkajärvi with formal international rules: a minimum carried weight, a standard obstacle course, and a time penalty for dropping your partner."],["Defense","Lead with the rulebook. A joke does not need a minimum weight requirement and a drop penalty — a sanctioned competition does."]]$uv$::jsonb),
  ($uv$62d5b7$uv$, $uv$fake$uv$, $uv$Global coffee shortage imminent as Brazil implements a 50% export ban to prioritise domestic reserves amid climate anomalies.$uv$, $uv$[["Precedent","Major agricultural exporters do have a history of invoking emergency protectionist measures during severe climate shocks."],["Context","The announcement allegedly surfaced just as commodity markets closed for the weekend, triggering panic-buying among European roasters."],["Defense","Lean into real anxieties about frost in South America and shifting weather patterns to make sudden government intervention sound inevitable."]]$uv$::jsonb, $uv$Attaches a fabricated specific (a 50% ban) to a real general trend (climate pressure on coffee). The weekend timing conveniently explains why nobody can verify it yet.$uv$, null),
  ($uv$0f7a4e$uv$, $uv$fake$uv$, $uv$Major social media platforms announce a mandatory monthly subscription fee for users who wish to keep their data hidden from corporate AI training models.$uv$, $uv$[["Precedent","Tech firms face heavy regulatory pressure over content scraping, and analysts speculate constantly about future monetisation tiers."],["Context","The change was supposedly leaked via an internal memo describing a tiered model for accounts seeking full opt-out protection."],["Defense","Frame it as the logical endpoint of platform economics — if they can monetise your data, they can charge you to stop."]]$uv$::jsonb, $uv$Cynicism substitutes for evidence. “Of course they would” feels like confirmation. The unnamed leaked memo is unfalsifiable by design.$uv$, null),
  ($uv$b4e91d$uv$, $uv$fake$uv$, $uv$World Health Organization issues a global warning advising citizens to avoid plastic water bottles left in direct sunlight due to a newly discovered neurotoxin.$uv$, $uv$[["Precedent","Health agencies do issue warnings about microplastics and chemical leaching under thermal stress."],["Context","The alert was allegedly distributed via an emergency bulletin about bottled water left in hot vehicles."],["Defense","Use terminology about polymer breakdown and chemical toxicity to suggest a suppressed safety warning finally surfacing."]]$uv$::jsonb, $uv$A real forwarded-message hoax with a decade of circulation. Borrowing a genuine agency's authority for an invented finding is the most common health-misinformation pattern there is.$uv$, null),
  ($uv$8c26f0$uv$, $uv$fake$uv$, $uv$The European Union passes legislation requiring all smartphone manufacturers to include a built-in breathalyser that disables messaging apps after midnight.$uv$, $uv$[["Precedent","The EU genuinely does pass aggressive standardised hardware mandates on manufacturers selling into the bloc, such as the USB-C charging requirement."],["Context","The regulation was reportedly driven by transport safety committees seeking to curb late-night incidents."],["Defense","Argue that EU regulators prioritise public safety over convenience and that hardware-level safety integration is becoming normal."]]$uv$::jsonb, $uv$One true precedent (USB-C) is used to license an absurd extrapolation. Test the leap, not the premise.$uv$, null),
  ($uv$17b3ce$uv$, $uv$fake$uv$, $uv$NASA confirms a newly discovered asteroid is composed entirely of solid platinum and will pass close enough to Earth to be mined with standard commercial rockets by 2030.$uv$, $uv$[["Precedent","Agencies have genuinely mapped near-Earth metallic asteroids valued in the trillions."],["Context","The timeline was supposedly fast-tracked after a rocket startup secured a multi-billion-dollar defence subsidy."],["Defense","Hype the commercial stakes and the billionaire space race; insist the interception technology already exists."]]$uv$::jsonb, $uv$“Composed entirely of solid platinum” and “standard commercial rockets” are both quietly impossible, buried under a real research programme.$uv$, null),
  ($uv$d38025$uv$, $uv$fake$uv$, $uv$The Netherlands will convert every motorway lane to load-bearing solar panels by 2032, funding the rollout entirely from the electricity generated.$uv$, $uv$[["Precedent","The country genuinely piloted a solar cycle path, and its infrastructure agency has a real reputation for experimental road technology."],["Context","The programme was reportedly approved after a pilot stretch outperformed rooftop installations in winter output."],["Defense","Emphasise the self-funding mechanism — once a road pays for itself, no politician needs to justify the budget."]]$uv$::jsonb, $uv$A real, tiny pilot inflated to a national mandate. The self-funding claim removes the obvious objection before anyone raises it.$uv$, null),
  ($uv$4e7c8a$uv$, $uv$fake$uv$, $uv$Airlines will begin charging passengers by combined body and baggage weight from 2027 under new international fuel-efficiency rules.$uv$, $uv$[["Precedent","Fuel burn genuinely scales with total aircraft weight, and airlines already price checked baggage by the kilogram."],["Context","The scheme was reportedly agreed at an industry association summit as part of emissions-reduction commitments."],["Defense","Argue the physics is undeniable and that extending existing baggage pricing to total load is merely consistent."]]$uv$::jsonb, $uv$The underlying physics is true, so the policy inherits its credibility. The invented part is that any regulator mandated it.$uv$, null),
  ($uv$a91f56$uv$, $uv$fake$uv$, $uv$Japan becomes the first country to make a four-day working week legally mandatory for all employers, with criminal penalties for violations.$uv$, $uv$[["Precedent","The Japanese government genuinely has published guidance encouraging shorter working weeks, and the country has real, well-documented overwork legislation."],["Context","The law was reportedly accelerated by demographic pressure and a series of high-profile overwork cases."],["Defense","Point to Japan's existing overtime caps as proof that this government legislates working hours aggressively."]]$uv$::jsonb, $uv$Converts a real recommendation into a fabricated mandate. The distinction between “encouraged” and “required” is where most policy misinformation lives.$uv$, null),
  ($uv$5d0e73$uv$, $uv$fake$uv$, $uv$UNESCO adds internet memes to its Intangible Cultural Heritage list, recognising them as a protected form of global folk expression.$uv$, $uv$[["Precedent","The Intangible Cultural Heritage list genuinely covers oral traditions, social practices and folk expression rather than physical monuments."],["Context","The listing was reportedly proposed by a bloc of member states seeking recognition for digital-native culture."],["Defense","Argue memes are demonstrably folk expression transmitted culturally — a textbook fit for the category as it is actually defined."]]$uv$::jsonb, $uv$The category genuinely almost fits, which is the trap. Plausible categorisation is not evidence that a nomination occurred; inscriptions come from named states, in named sessions, on the record.$uv$, null),
  ($uv$e2648b$uv$, $uv$fake$uv$, $uv$Several countries move to impose a nightly screen curfew for under-16s after a study linked blue light to permanent retinal cell damage.$uv$, $uv$[["Precedent","Multiple governments have genuinely legislated minimum ages and time limits for minors' social media access."],["Context","The curfew was reportedly triggered by an ophthalmology study circulated ahead of peer review."],["Defense","Combine real parental anxiety about screen time with clinical-sounding language about photoreceptor degradation."]]$uv$::jsonb, $uv$A real legislative trend plus an invented medical justification. “Circulated ahead of peer review” is doing all the work — it explains away the absence of a citation.$uv$, null),
  ($uv$f7a103$uv$, $uv$audience$uv$, null, null, null, null),
  ($uv$36ce8f$uv$, $uv$audience$uv$, null, null, null, null),
  ($uv$9b40d2$uv$, $uv$audience$uv$, null, null, null, null),
  ($uv$0e85b6$uv$, $uv$audience$uv$, null, null, null, null),
  ($uv$c2df47$uv$, $uv$audience$uv$, null, null, null, null),
  ($uv$81594e$uv$, $uv$audience$uv$, null, null, null, null)
on conflict (slug) do update set
  type         = excluded.type,
  headline     = excluded.headline,
  clues        = excluded.clues,
  why_it_works = excluded.why_it_works,
  verification = excluded.verification;

-- Fail loudly rather than let a game start on a half-loaded deck.
do $$
declare r int; f int; a int;
begin
  select count(*) into r from public.cards where type = 'real';
  select count(*) into f from public.cards where type = 'fake';
  select count(*) into a from public.cards where type = 'audience';
  if r <> 20 or f <> 10 or a <> 6 then
    raise exception 'card table is %/%/% , expected 20/10/6', r, f, a;
  end if;
  if exists (select 1 from public.cards where type <> 'audience' and headline is null) then
    raise exception 'a press card is missing its headline';
  end if;
  -- Clue asymmetry: fabrications carry player-facing clues, verified stories
  -- do not. A real card with clues would hand its journalist an argument the
  -- design deliberately withholds.
  if exists (select 1 from public.cards
              where type = 'fake' and (clues is null or jsonb_array_length(clues) <> 3)) then
    raise exception 'a fabricated card does not have exactly 3 clues';
  end if;
  if exists (select 1 from public.cards where type = 'real' and clues is not null) then
    raise exception 'a verified card carries player-facing clues; they belong in verification';
  end if;
  if exists (select 1 from public.cards
              where type = 'real' and (verification is null or jsonb_array_length(verification) <> 3)) then
    raise exception 'a verified card is missing its 3 facilitator verification notes';
  end if;
  if exists (select 1 from public.cards
              where type = 'audience' and (headline is not null or clues is not null)) then
    raise exception 'an audience card carries content it should not have';
  end if;
  raise notice 'cards loaded: % real, % fake, % audience', r, f, a;
end $$;
